version: "2"

services:
  grandgrz_db:
    image: postgres:14
    container_name: grandgrz_db
    volumes:
      - ~/.pg/pg_data/data:/var/lib/postgresql/data
    env_file:
      - .env
  grandgrz_project:
    image: grandgrz:latest
    container_name: grandgrz
    depends_on:
      - grandgrz_db
    volumes:
      - static_volume:/grandgrz/static
      - media_volume:/grandgrz/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 grandgrz.wsgi:application"
  grandgrz_nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: grandgrz_nginx
    image: grandgrz_nginx
    volumes:
      - static_volume:/grandgrz/static
      - media_volume:/grandgrz/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - grandgrz_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: grandgrz_acme
    volumes_from:
      - grandgrz_nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme: