# Generated by Django 4.2.5 on 2023-10-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('house', 'Дом'), ('flat', 'квартира')], default='house', max_length=10, verbose_name='Наименование')),
                ('area', models.FloatField(verbose_name='Общая площадь')),
                ('rooms', models.IntegerField(default=1, verbose_name='Количество комнат')),
                ('material', models.CharField(max_length=128, verbose_name='Материал стен')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен к продаже?')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['area'],
            },
        ),
    ]
