# Generated by Django 4.2.5 on 2023-10-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(verbose_name='Общая площадь')),
                ('rooms', models.IntegerField(default=1, verbose_name='Количество комнат')),
                ('material', models.CharField(max_length=128, verbose_name='Материал стен')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='agency/%Y/%m/%d', verbose_name='Изображение')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен к продаже?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='agency.category')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['available'],
            },
        ),
    ]
