# Generated by Django 4.2.5 on 2023-10-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_estate_name_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='best_offer',
            field=models.BooleanField(default=False, verbose_name='Лучшее предложение'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='material',
            field=models.CharField(blank=True, max_length=128, verbose_name='Материал стен'),
        ),
    ]
