# Generated by Django 4.2.5 on 2023-10-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_estate_options_estateimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estateimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='estate',
            name='image',
        ),
    ]
