# Generated by Django 4.2.5 on 2023-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_estate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.FloatField(blank=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rooms',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество комнат'),
        ),
    ]
