# Generated by Django 4.2.5 on 2023-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_workers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='workers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='workers/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
