# Generated by Django 4.2.5 on 2023-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_workers_options_alter_workers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='phone',
            field=models.CharField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
    ]
