# Generated by Django 4.2.5 on 2023-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_remove_category_slug_remove_estate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=256, verbose_name='Банк получателя')),
                ('bick', models.CharField(max_length=128, verbose_name='БИК')),
                ('account', models.CharField(max_length=128, verbose_name='Р/счёт')),
                ('corr_account', models.CharField(max_length=128, verbose_name='Корр. счет')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
