# Generated by Django 4.2.5 on 2023-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='bank',
            field=models.CharField(max_length=256, verbose_name='Банк получателя'),
        ),
    ]
